name: spatial-inequality
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - matplotlib
  - pandas
  - jupyter
  - descartes
  - geopandas
  - pygmo
  - requests
  - contextily
  - flask
  - gunicorn
  - pip:
    - -r requirements.txt
